import * as si from "simple-icons";

export type LibraryIcon = {
  id: string;
  name: string;
  svgDataUri: string;
  color: string;
  category: "microsoft" | "browser" | "dev" | "creative" | "social" | "media" | "productivity" | "gaming" | "win7";
};

function encode(svg: string): string {
  return `data:image/svg+xml;base64,${typeof window === "undefined" ? Buffer.from(svg).toString("base64") : btoa(unescape(encodeURIComponent(svg)))}`;
}

function siToUri(icon: { svg: string; hex: string }, forceWhite = false): string {
  const fill = forceWhite ? "ffffff" : icon.hex;
  return encode(icon.svg.replace("<svg ", `<svg fill="#${fill}" `));
}

// Microsoft Office — MIT (sempostma/office365-icons)
const MS_APPS: LibraryIcon[] = [
  { id: "ms-word",       name: "Word",       svgDataUri: "/ms-icons/word.svg",       color: "#2B579A", category: "microsoft" },
  { id: "ms-excel",      name: "Excel",      svgDataUri: "/ms-icons/excel.svg",      color: "#217346", category: "microsoft" },
  { id: "ms-powerpoint", name: "PowerPoint", svgDataUri: "/ms-icons/powerpoint.svg", color: "#B7472A", category: "microsoft" },
  { id: "ms-outlook",    name: "Outlook",    svgDataUri: "/ms-icons/outlook.svg",    color: "#0078D4", category: "microsoft" },
  { id: "ms-teams",      name: "Teams",      svgDataUri: "/ms-icons/teams.svg",      color: "#6264A7", category: "microsoft" },
  { id: "ms-onedrive",   name: "OneDrive",   svgDataUri: "/ms-icons/onedrive.svg",   color: "#0078D4", category: "microsoft" },
  { id: "ms-onenote",    name: "OneNote",    svgDataUri: "/ms-icons/onenote.svg",    color: "#7719AA", category: "microsoft" },
  { id: "ms-sharepoint", name: "SharePoint", svgDataUri: "/ms-icons/sharepoint.svg", color: "#036C70", category: "microsoft" },
];

// Browser icons — official colorful PNGs from cdnjs browser-logos (MIT)
const BROWSER_ICONS: LibraryIcon[] = [
  { id: "browser-chrome",  name: "Chrome",  svgDataUri: "/browser-icons/chrome.png",  color: "#4285F4", category: "browser" },
  { id: "browser-firefox", name: "Firefox", svgDataUri: "/browser-icons/firefox.png", color: "#FF7139", category: "browser" },
  { id: "browser-edge",    name: "Edge",    svgDataUri: "/browser-icons/edge.png",    color: "#0078D4", category: "browser" },
  { id: "browser-brave",   name: "Brave",   svgDataUri: "/browser-icons/brave.png",   color: "#FB542B", category: "browser" },
  { id: "browser-opera",   name: "Opera",   svgDataUri: "/browser-icons/opera.png",   color: "#FF1B2D", category: "browser" },
];

type SiEntry = { slug: string; name: string; whiteOnly?: boolean; category: LibraryIcon["category"] };

const SI_APPS: SiEntry[] = [
  { slug: "siArc",               name: "Arc",          whiteOnly: true, category: "browser" },
  { slug: "siSafari",            name: "Safari",                        category: "browser" },
  { slug: "siVscodium",          name: "VS Code",                       category: "dev" },
  { slug: "siGithub",            name: "GitHub",       whiteOnly: true, category: "dev" },
  { slug: "siGit",               name: "Git",                           category: "dev" },
  { slug: "siDocker",            name: "Docker",                        category: "dev" },
  { slug: "siPostman",           name: "Postman",                       category: "dev" },
  { slug: "siIntellijidea",      name: "IntelliJ",     whiteOnly: true, category: "dev" },
  { slug: "siFigma",             name: "Figma",                         category: "creative" },
  { slug: "siAdobephotoshop",    name: "Photoshop",                     category: "creative" },
  { slug: "siAdobeillustrator",  name: "Illustrator",                   category: "creative" },
  { slug: "siAdobepremierepro",  name: "Premiere",                      category: "creative" },
  { slug: "siAdobelightroom",    name: "Lightroom",                     category: "creative" },
  { slug: "siAdobeaftereffects", name: "After Effects",                 category: "creative" },
  { slug: "siBlender",           name: "Blender",                       category: "creative" },
  { slug: "siCanva",             name: "Canva",                         category: "creative" },
  { slug: "siDiscord",           name: "Discord",                       category: "social" },
  { slug: "siSlack",             name: "Slack",                         category: "social" },
  { slug: "siWhatsapp",          name: "WhatsApp",                      category: "social" },
  { slug: "siTelegram",          name: "Telegram",                      category: "social" },
  { slug: "siX",                 name: "X",            whiteOnly: true, category: "social" },
  { slug: "siInstagram",         name: "Instagram",                     category: "social" },
  { slug: "siFacebook",          name: "Facebook",                      category: "social" },
  { slug: "siLinkedin",          name: "LinkedIn",                      category: "social" },
  { slug: "siReddit",            name: "Reddit",                        category: "social" },
  { slug: "siSignal",            name: "Signal",                        category: "social" },
  { slug: "siZoom",              name: "Zoom",                          category: "social" },
  { slug: "siSpotify",           name: "Spotify",                       category: "media" },
  { slug: "siYoutube",           name: "YouTube",                       category: "media" },
  { slug: "siNetflix",           name: "Netflix",                       category: "media" },
  { slug: "siVlcmediaplayer",    name: "VLC",                           category: "media" },
  { slug: "siObsstudio",         name: "OBS",                           category: "media" },
  { slug: "siPrimevideo",        name: "Prime Video",                   category: "media" },
  { slug: "siAppletv",           name: "Apple TV",     whiteOnly: true, category: "media" },
  { slug: "siGmail",             name: "Gmail",                         category: "productivity" },
  { slug: "siGoogledrive",       name: "Drive",                         category: "productivity" },
  { slug: "siDropbox",           name: "Dropbox",                       category: "productivity" },
  { slug: "siGooglecalendar",    name: "Calendar",                      category: "productivity" },
  { slug: "siNotion",            name: "Notion",       whiteOnly: true, category: "productivity" },
  { slug: "siObsidian",          name: "Obsidian",                      category: "productivity" },
  { slug: "siTodoist",           name: "Todoist",                       category: "productivity" },
  { slug: "siTrello",            name: "Trello",                        category: "productivity" },
  { slug: "siEvernote",          name: "Evernote",                      category: "productivity" },
  { slug: "siSteam",             name: "Steam",        whiteOnly: true, category: "gaming" },
  { slug: "siEpicgames",         name: "Epic",         whiteOnly: true, category: "gaming" },
  { slug: "siGogdotcom",         name: "GOG",          whiteOnly: true, category: "gaming" },
  { slug: "siRiotgames",         name: "Riot",                          category: "gaming" },
  { slug: "siTwitch",            name: "Twitch",                        category: "gaming" },
];

const SI_ICONS: LibraryIcon[] = SI_APPS
  .map(({ slug, name, whiteOnly, category }) => {
    // @ts-expect-error - dynamic access
    const icon = si[slug];
    if (!icon) return null;
    return { id: slug, name, color: `#${icon.hex}`, svgDataUri: siToUri(icon, whiteOnly), category } as LibraryIcon;
  })
  .filter(Boolean) as LibraryIcon[];

// Windows 7 native icons — extracted from official shell32.dll + imageres.dll
// Source: bartekl1/windows-ui-assets (educational/archival use)
const WIN7_ICONS: LibraryIcon[] = [
  { id: "w7-shell32_141", name: "Add User", svgDataUri: "/w7-assets/icons/shell32_141.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_307", name: "Address Bar", svgDataUri: "/w7-assets/icons/shell32_307.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_143", name: "Admin", svgDataUri: "/w7-assets/icons/shell32_143.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1004", name: "Arrow Down", svgDataUri: "/w7-assets/icons/shell32_1004.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1003", name: "Arrow Up", svgDataUri: "/w7-assets/icons/shell32_1003.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_308", name: "Back", svgDataUri: "/w7-assets/icons/shell32_308.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_266", name: "Backup", svgDataUri: "/w7-assets/icons/shell32_266.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_49", name: "Battery", svgDataUri: "/w7-assets/icons/imageres_49.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_338", name: "Blocked", svgDataUri: "/w7-assets/icons/shell32_338.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_178", name: "Blu-ray", svgDataUri: "/w7-assets/icons/imageres_178.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_37", name: "Bluetooth", svgDataUri: "/w7-assets/icons/imageres_37.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_167", name: "Bookmarks", svgDataUri: "/w7-assets/icons/shell32_167.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_40", name: "Briefcase", svgDataUri: "/w7-assets/icons/shell32_40.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_41", name: "Briefcase (Open)", svgDataUri: "/w7-assets/icons/shell32_41.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_247", name: "Brightness", svgDataUri: "/w7-assets/icons/shell32_247.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_232", name: "Burn", svgDataUri: "/w7-assets/icons/shell32_232.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_177", name: "CD", svgDataUri: "/w7-assets/icons/imageres_177.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_50", name: "CD Drive", svgDataUri: "/w7-assets/icons/shell32_50.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_44", name: "CD ROM", svgDataUri: "/w7-assets/icons/shell32_44.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_22", name: "CD/DVD Drive", svgDataUri: "/w7-assets/icons/shell32_22.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_173", name: "Calendar", svgDataUri: "/w7-assets/icons/shell32_173.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_29", name: "Camera", svgDataUri: "/w7-assets/icons/imageres_29.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_147", name: "Certificate", svgDataUri: "/w7-assets/icons/shell32_147.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_157", name: "Checkmark", svgDataUri: "/w7-assets/icons/shell32_157.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_258", name: "ClearType", svgDataUri: "/w7-assets/icons/shell32_258.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_174", name: "Clock", svgDataUri: "/w7-assets/icons/shell32_174.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_200", name: "Close", svgDataUri: "/w7-assets/icons/shell32_200.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_257", name: "Color Calibrate", svgDataUri: "/w7-assets/icons/shell32_257.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_220", name: "Color Palette", svgDataUri: "/w7-assets/icons/shell32_220.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_299", name: "Column Header", svgDataUri: "/w7-assets/icons/shell32_299.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1001", name: "Computer", svgDataUri: "/w7-assets/icons/imageres_1001.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_15", name: "Computer (Old)", svgDataUri: "/w7-assets/icons/shell32_15.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_278", name: "Computer Management", svgDataUri: "/w7-assets/icons/shell32_278.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_37", name: "Connect", svgDataUri: "/w7-assets/icons/shell32_37.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_259", name: "Connect Display", svgDataUri: "/w7-assets/icons/shell32_259.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_176", name: "Contacts", svgDataUri: "/w7-assets/icons/shell32_176.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_100", name: "Control Panel", svgDataUri: "/w7-assets/icons/imageres_100.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_137", name: "Control Panel", svgDataUri: "/w7-assets/icons/shell32_137.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_169", name: "Copy", svgDataUri: "/w7-assets/icons/shell32_169.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_245", name: "Crop", svgDataUri: "/w7-assets/icons/shell32_245.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1008", name: "Cut", svgDataUri: "/w7-assets/icons/shell32_1008.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_176", name: "DVD", svgDataUri: "/w7-assets/icons/imageres_176.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_39", name: "DVD Drive", svgDataUri: "/w7-assets/icons/imageres_39.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_51", name: "DVD Drive", svgDataUri: "/w7-assets/icons/shell32_51.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_43", name: "DVD ROM", svgDataUri: "/w7-assets/icons/shell32_43.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_184", name: "Database", svgDataUri: "/w7-assets/icons/shell32_184.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_269", name: "Defragment", svgDataUri: "/w7-assets/icons/shell32_269.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1006", name: "Delete", svgDataUri: "/w7-assets/icons/shell32_1006.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_314", name: "Deselect", svgDataUri: "/w7-assets/icons/shell32_314.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_6", name: "Desktop", svgDataUri: "/w7-assets/icons/imageres_6.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_194", name: "Desktop Shortcut", svgDataUri: "/w7-assets/icons/shell32_194.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_294", name: "Details Pane", svgDataUri: "/w7-assets/icons/shell32_294.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_276", name: "Device Manager", svgDataUri: "/w7-assets/icons/shell32_276.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_263", name: "Dial-up", svgDataUri: "/w7-assets/icons/shell32_263.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_337", name: "Disconnect", svgDataUri: "/w7-assets/icons/shell32_337.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_38", name: "Disconnect Net", svgDataUri: "/w7-assets/icons/shell32_38.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_268", name: "Disk Cleanup", svgDataUri: "/w7-assets/icons/shell32_268.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_277", name: "Disk Management", svgDataUri: "/w7-assets/icons/shell32_277.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_255", name: "Display", svgDataUri: "/w7-assets/icons/shell32_255.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_2", name: "Document", svgDataUri: "/w7-assets/icons/imageres_2.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_2", name: "Document (Alt)", svgDataUri: "/w7-assets/icons/shell32_2.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1", name: "Document File", svgDataUri: "/w7-assets/icons/shell32_1.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1002", name: "Documents", svgDataUri: "/w7-assets/icons/imageres_1002.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1013", name: "Downloads", svgDataUri: "/w7-assets/icons/imageres_1013.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_17", name: "Drive (Network)", svgDataUri: "/w7-assets/icons/shell32_17.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_311", name: "Edit (Text)", svgDataUri: "/w7-assets/icons/shell32_311.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_243", name: "Edit Photo", svgDataUri: "/w7-assets/icons/shell32_243.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_331", name: "Eject", svgDataUri: "/w7-assets/icons/shell32_331.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_175", name: "Email", svgDataUri: "/w7-assets/icons/shell32_175.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_250", name: "Email Photo", svgDataUri: "/w7-assets/icons/shell32_250.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_231", name: "Equalizer", svgDataUri: "/w7-assets/icons/shell32_231.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_271", name: "Event Log", svgDataUri: "/w7-assets/icons/shell32_271.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_185", name: "Executable", svgDataUri: "/w7-assets/icons/shell32_185.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_325", name: "Exit", svgDataUri: "/w7-assets/icons/shell32_325.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_242", name: "Export", svgDataUri: "/w7-assets/icons/shell32_242.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_24", name: "Fax", svgDataUri: "/w7-assets/icons/shell32_24.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_29", name: "Fax (Receive)", svgDataUri: "/w7-assets/icons/shell32_29.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_28", name: "Fax (Send)", svgDataUri: "/w7-assets/icons/shell32_28.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_192", name: "Feed", svgDataUri: "/w7-assets/icons/shell32_192.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_315", name: "Find", svgDataUri: "/w7-assets/icons/shell32_315.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_33", name: "Find Files", svgDataUri: "/w7-assets/icons/shell32_33.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_148", name: "Firewall", svgDataUri: "/w7-assets/icons/shell32_148.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_264", name: "Firewall Alt", svgDataUri: "/w7-assets/icons/shell32_264.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_42", name: "Floppy", svgDataUri: "/w7-assets/icons/shell32_42.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_3", name: "Folder", svgDataUri: "/w7-assets/icons/imageres_3.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_4", name: "Folder (Classic)", svgDataUri: "/w7-assets/icons/shell32_4.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_5", name: "Folder (Closed)", svgDataUri: "/w7-assets/icons/shell32_5.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_5", name: "Folder (Compressed)", svgDataUri: "/w7-assets/icons/imageres_5.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_7", name: "Folder (Compressed)", svgDataUri: "/w7-assets/icons/shell32_7.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_11", name: "Folder (Docs Open)", svgDataUri: "/w7-assets/icons/shell32_11.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_10", name: "Folder (Docs)", svgDataUri: "/w7-assets/icons/shell32_10.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_26", name: "Folder (Encrypted)", svgDataUri: "/w7-assets/icons/imageres_26.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_8", name: "Folder (Encrypted)", svgDataUri: "/w7-assets/icons/shell32_8.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_9", name: "Folder (Linked)", svgDataUri: "/w7-assets/icons/shell32_9.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_20", name: "Folder (Network)", svgDataUri: "/w7-assets/icons/imageres_20.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_22", name: "Folder (Open Alt)", svgDataUri: "/w7-assets/icons/imageres_22.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_3", name: "Folder (Open Tree)", svgDataUri: "/w7-assets/icons/shell32_3.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_102", name: "Folder (Open)", svgDataUri: "/w7-assets/icons/imageres_102.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_14", name: "Folder (Open)", svgDataUri: "/w7-assets/icons/shell32_14.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_25", name: "Folder (Private)", svgDataUri: "/w7-assets/icons/imageres_25.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_23", name: "Folder (Search)", svgDataUri: "/w7-assets/icons/imageres_23.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_24", name: "Folder (Shared)", svgDataUri: "/w7-assets/icons/imageres_24.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_6", name: "Folder (Shared)", svgDataUri: "/w7-assets/icons/shell32_6.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_16", name: "Folder (Tree)", svgDataUri: "/w7-assets/icons/shell32_16.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_27", name: "Folder (Virtual)", svgDataUri: "/w7-assets/icons/imageres_27.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_21", name: "Folder (Yellow)", svgDataUri: "/w7-assets/icons/imageres_21.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_4", name: "Folder Alt", svgDataUri: "/w7-assets/icons/imageres_4.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_309", name: "Forward", svgDataUri: "/w7-assets/icons/shell32_309.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_38", name: "Game Controller", svgDataUri: "/w7-assets/icons/imageres_38.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_103", name: "Games", svgDataUri: "/w7-assets/icons/imageres_103.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_160", name: "Globe", svgDataUri: "/w7-assets/icons/shell32_160.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_161", name: "Globe (Alt)", svgDataUri: "/w7-assets/icons/shell32_161.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_317", name: "Go To", svgDataUri: "/w7-assets/icons/shell32_317.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_44", name: "Graphics Card", svgDataUri: "/w7-assets/icons/imageres_44.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_142", name: "Group", svgDataUri: "/w7-assets/icons/shell32_142.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_297", name: "Group By", svgDataUri: "/w7-assets/icons/shell32_297.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_17", name: "Hard Drive", svgDataUri: "/w7-assets/icons/imageres_17.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_46", name: "Hard Drive (Fixed)", svgDataUri: "/w7-assets/icons/shell32_46.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_45", name: "Hard Drive (Local)", svgDataUri: "/w7-assets/icons/shell32_45.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_47", name: "Hard Drive (Removable)", svgDataUri: "/w7-assets/icons/shell32_47.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1001", name: "Help", svgDataUri: "/w7-assets/icons/shell32_1001.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_30", name: "Help", svgDataUri: "/w7-assets/icons/shell32_30.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_166", name: "History", svgDataUri: "/w7-assets/icons/shell32_166.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_306", name: "Home", svgDataUri: "/w7-assets/icons/shell32_306.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_281", name: "HomeGroup", svgDataUri: "/w7-assets/icons/shell32_281.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_134", name: "IE (Flag)", svgDataUri: "/w7-assets/icons/shell32_134.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_135", name: "IE (Small)", svgDataUri: "/w7-assets/icons/shell32_135.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_512", name: "IE Classic", svgDataUri: "/w7-assets/icons/shell32_512.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_180", name: "Image", svgDataUri: "/w7-assets/icons/shell32_180.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_241", name: "Import Photos", svgDataUri: "/w7-assets/icons/shell32_241.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_156", name: "Info", svgDataUri: "/w7-assets/icons/shell32_156.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_133", name: "Internet Explorer", svgDataUri: "/w7-assets/icons/shell32_133.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_313", name: "Invert Select", svgDataUri: "/w7-assets/icons/shell32_313.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_292", name: "Jump List", svgDataUri: "/w7-assets/icons/shell32_292.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_32", name: "Keyboard", svgDataUri: "/w7-assets/icons/imageres_32.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_196", name: "Layout", svgDataUri: "/w7-assets/icons/shell32_196.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_186", name: "Library", svgDataUri: "/w7-assets/icons/shell32_186.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_284", name: "Library Add", svgDataUri: "/w7-assets/icons/shell32_284.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_145", name: "Locked", svgDataUri: "/w7-assets/icons/shell32_145.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_153", name: "Magnifier", svgDataUri: "/w7-assets/icons/shell32_153.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_210", name: "Magnifier Tool", svgDataUri: "/w7-assets/icons/shell32_210.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_39", name: "Mapped Drive", svgDataUri: "/w7-assets/icons/shell32_39.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_199", name: "Maximize", svgDataUri: "/w7-assets/icons/shell32_199.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_224", name: "Media (Next)", svgDataUri: "/w7-assets/icons/shell32_224.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_222", name: "Media (Pause)", svgDataUri: "/w7-assets/icons/shell32_222.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_221", name: "Media (Play)", svgDataUri: "/w7-assets/icons/shell32_221.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_225", name: "Media (Prev)", svgDataUri: "/w7-assets/icons/shell32_225.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_223", name: "Media (Stop)", svgDataUri: "/w7-assets/icons/shell32_223.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_41", name: "Media Card", svgDataUri: "/w7-assets/icons/imageres_41.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_174", name: "Media Player", svgDataUri: "/w7-assets/icons/imageres_174.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_301", name: "Menu Bar", svgDataUri: "/w7-assets/icons/shell32_301.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_198", name: "Minimize", svgDataUri: "/w7-assets/icons/shell32_198.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_34", name: "Monitor", svgDataUri: "/w7-assets/icons/imageres_34.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_47", name: "Motherboard", svgDataUri: "/w7-assets/icons/imageres_47.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_33", name: "Mouse", svgDataUri: "/w7-assets/icons/imageres_33.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1004", name: "Music", svgDataUri: "/w7-assets/icons/imageres_1004.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_182", name: "Music File", svgDataUri: "/w7-assets/icons/shell32_182.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_227", name: "Mute", svgDataUri: "/w7-assets/icons/shell32_227.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_295", name: "Navigation Pane", svgDataUri: "/w7-assets/icons/shell32_295.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1010", name: "Network", svgDataUri: "/w7-assets/icons/imageres_1010.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_23", name: "Network", svgDataUri: "/w7-assets/icons/shell32_23.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_42", name: "Network Card", svgDataUri: "/w7-assets/icons/imageres_42.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_19", name: "Network Drive", svgDataUri: "/w7-assets/icons/imageres_19.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_48", name: "Network Drive", svgDataUri: "/w7-assets/icons/shell32_48.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_19", name: "Network Globe", svgDataUri: "/w7-assets/icons/shell32_19.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_36", name: "Network Globe", svgDataUri: "/w7-assets/icons/shell32_36.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_27", name: "Network Printer", svgDataUri: "/w7-assets/icons/shell32_27.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_49", name: "Network Share", svgDataUri: "/w7-assets/icons/shell32_49.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_318", name: "New File", svgDataUri: "/w7-assets/icons/shell32_318.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1007", name: "New Folder", svgDataUri: "/w7-assets/icons/shell32_1007.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_303", name: "New Window", svgDataUri: "/w7-assets/icons/shell32_303.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_178", name: "Notes", svgDataUri: "/w7-assets/icons/shell32_178.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_319", name: "Open File", svgDataUri: "/w7-assets/icons/shell32_319.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_251", name: "Order Prints", svgDataUri: "/w7-assets/icons/shell32_251.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_327", name: "Overlay Lock", svgDataUri: "/w7-assets/icons/shell32_327.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_330", name: "Overlay Offline", svgDataUri: "/w7-assets/icons/shell32_330.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_328", name: "Overlay Share", svgDataUri: "/w7-assets/icons/shell32_328.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_187", name: "Package", svgDataUri: "/w7-assets/icons/shell32_187.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_324", name: "Page Setup", svgDataUri: "/w7-assets/icons/shell32_324.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_170", name: "Paste", svgDataUri: "/w7-assets/icons/shell32_170.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_275", name: "Performance", svgDataUri: "/w7-assets/icons/shell32_275.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_31", name: "Phone", svgDataUri: "/w7-assets/icons/imageres_31.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_53", name: "Phone Device", svgDataUri: "/w7-assets/icons/shell32_53.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_239", name: "Photo", svgDataUri: "/w7-assets/icons/shell32_239.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1003", name: "Pictures", svgDataUri: "/w7-assets/icons/imageres_1003.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_291", name: "Pinned Items", svgDataUri: "/w7-assets/icons/shell32_291.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_230", name: "Playlist", svgDataUri: "/w7-assets/icons/shell32_230.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_193", name: "Podcast", svgDataUri: "/w7-assets/icons/shell32_193.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_274", name: "Policies", svgDataUri: "/w7-assets/icons/shell32_274.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_48", name: "Power", svgDataUri: "/w7-assets/icons/imageres_48.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_293", name: "Preview Pane", svgDataUri: "/w7-assets/icons/shell32_293.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_168", name: "Print", svgDataUri: "/w7-assets/icons/shell32_168.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_322", name: "Print (File)", svgDataUri: "/w7-assets/icons/shell32_322.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_248", name: "Print Photo", svgDataUri: "/w7-assets/icons/shell32_248.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_323", name: "Print Preview", svgDataUri: "/w7-assets/icons/shell32_323.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_28", name: "Printer", svgDataUri: "/w7-assets/icons/imageres_28.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_25", name: "Printer", svgDataUri: "/w7-assets/icons/shell32_25.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_26", name: "Printer Alt", svgDataUri: "/w7-assets/icons/shell32_26.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_45", name: "Processor", svgDataUri: "/w7-assets/icons/imageres_45.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_260", name: "Projector", svgDataUri: "/w7-assets/icons/shell32_260.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1005", name: "Properties", svgDataUri: "/w7-assets/icons/shell32_1005.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_172", name: "Properties", svgDataUri: "/w7-assets/icons/shell32_172.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_283", name: "Public Folder", svgDataUri: "/w7-assets/icons/shell32_283.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_46", name: "RAM", svgDataUri: "/w7-assets/icons/imageres_46.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_52", name: "RAM Drive", svgDataUri: "/w7-assets/icons/shell32_52.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_236", name: "Radio", svgDataUri: "/w7-assets/icons/shell32_236.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_290", name: "Recent Items", svgDataUri: "/w7-assets/icons/shell32_290.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_9", name: "Recycle Bin (Empty)", svgDataUri: "/w7-assets/icons/imageres_9.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_154", name: "Recycle Bin (Empty)", svgDataUri: "/w7-assets/icons/shell32_154.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_8", name: "Recycle Bin (Full)", svgDataUri: "/w7-assets/icons/imageres_8.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_155", name: "Recycle Bin (Full)", svgDataUri: "/w7-assets/icons/shell32_155.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_244", name: "Red Eye", svgDataUri: "/w7-assets/icons/shell32_244.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_304", name: "Refresh", svgDataUri: "/w7-assets/icons/shell32_304.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_273", name: "Registry", svgDataUri: "/w7-assets/icons/shell32_273.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_279", name: "Remote Access", svgDataUri: "/w7-assets/icons/shell32_279.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_238", name: "Remote Control", svgDataUri: "/w7-assets/icons/shell32_238.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_20", name: "Remote Desktop", svgDataUri: "/w7-assets/icons/shell32_20.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_18", name: "Removable Drive", svgDataUri: "/w7-assets/icons/imageres_18.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_229", name: "Repeat", svgDataUri: "/w7-assets/icons/shell32_229.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_316", name: "Replace", svgDataUri: "/w7-assets/icons/shell32_316.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_256", name: "Resolution", svgDataUri: "/w7-assets/icons/shell32_256.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_165", name: "Restore", svgDataUri: "/w7-assets/icons/shell32_165.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_267", name: "Restore System", svgDataUri: "/w7-assets/icons/shell32_267.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_233", name: "Rip", svgDataUri: "/w7-assets/icons/shell32_233.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_246", name: "Rotate", svgDataUri: "/w7-assets/icons/shell32_246.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_329", name: "Run As Admin", svgDataUri: "/w7-assets/icons/shell32_329.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_320", name: "Save", svgDataUri: "/w7-assets/icons/shell32_320.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_321", name: "Save As", svgDataUri: "/w7-assets/icons/shell32_321.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_30", name: "Scanner", svgDataUri: "/w7-assets/icons/imageres_30.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_253", name: "Screensaver", svgDataUri: "/w7-assets/icons/shell32_253.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_152", name: "Search", svgDataUri: "/w7-assets/icons/shell32_152.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_31", name: "Search (Old)", svgDataUri: "/w7-assets/icons/shell32_31.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_289", name: "Search Result", svgDataUri: "/w7-assets/icons/shell32_289.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_139", name: "Security", svgDataUri: "/w7-assets/icons/shell32_139.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_312", name: "Select All", svgDataUri: "/w7-assets/icons/shell32_312.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_272", name: "Services", svgDataUri: "/w7-assets/icons/shell32_272.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_252", name: "Set Desktop", svgDataUri: "/w7-assets/icons/shell32_252.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_18", name: "Share", svgDataUri: "/w7-assets/icons/shell32_18.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_249", name: "Share Photo", svgDataUri: "/w7-assets/icons/shell32_249.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_282", name: "Share With", svgDataUri: "/w7-assets/icons/shell32_282.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_21", name: "Shared", svgDataUri: "/w7-assets/icons/shell32_21.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_35", name: "Shared Drive", svgDataUri: "/w7-assets/icons/shell32_35.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_34", name: "Shared Folder", svgDataUri: "/w7-assets/icons/shell32_34.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_138", name: "Shield", svgDataUri: "/w7-assets/icons/shell32_138.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_235", name: "Shop", svgDataUri: "/w7-assets/icons/shell32_235.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_326", name: "Shortcut Arrow", svgDataUri: "/w7-assets/icons/shell32_326.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_228", name: "Shuffle", svgDataUri: "/w7-assets/icons/shell32_228.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_191", name: "Slideshow", svgDataUri: "/w7-assets/icons/shell32_191.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_240", name: "Slideshow Start", svgDataUri: "/w7-assets/icons/shell32_240.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_296", name: "Sort", svgDataUri: "/w7-assets/icons/shell32_296.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_43", name: "Sound Card", svgDataUri: "/w7-assets/icons/imageres_43.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_35", name: "Speakers", svgDataUri: "/w7-assets/icons/imageres_35.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_197", name: "Split", svgDataUri: "/w7-assets/icons/shell32_197.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_300", name: "Status Bar", svgDataUri: "/w7-assets/icons/shell32_300.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_305", name: "Stop Loading", svgDataUri: "/w7-assets/icons/shell32_305.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_1002", name: "Sync", svgDataUri: "/w7-assets/icons/shell32_1002.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_234", name: "Sync Media", svgDataUri: "/w7-assets/icons/shell32_234.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_237", name: "TV", svgDataUri: "/w7-assets/icons/shell32_237.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_54", name: "Tablet", svgDataUri: "/w7-assets/icons/shell32_54.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_270", name: "Task Manager", svgDataUri: "/w7-assets/icons/shell32_270.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_177", name: "Tasks", svgDataUri: "/w7-assets/icons/shell32_177.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_183", name: "Text File", svgDataUri: "/w7-assets/icons/shell32_183.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_254", name: "Theme", svgDataUri: "/w7-assets/icons/shell32_254.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_302", name: "Toolbar", svgDataUri: "/w7-assets/icons/shell32_302.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_32", name: "Tree", svgDataUri: "/w7-assets/icons/shell32_32.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_40", name: "USB Drive", svgDataUri: "/w7-assets/icons/imageres_40.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_171", name: "Undo", svgDataUri: "/w7-assets/icons/shell32_171.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_146", name: "Unlocked", svgDataUri: "/w7-assets/icons/shell32_146.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_310", name: "Up", svgDataUri: "/w7-assets/icons/shell32_310.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_140", name: "User Account", svgDataUri: "/w7-assets/icons/shell32_140.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_144", name: "Users", svgDataUri: "/w7-assets/icons/shell32_144.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_262", name: "VPN", svgDataUri: "/w7-assets/icons/shell32_262.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_181", name: "Video", svgDataUri: "/w7-assets/icons/shell32_181.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_1008", name: "Videos", svgDataUri: "/w7-assets/icons/imageres_1008.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_298", name: "View Options", svgDataUri: "/w7-assets/icons/shell32_298.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_226", name: "Volume", svgDataUri: "/w7-assets/icons/shell32_226.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_151", name: "Warning", svgDataUri: "/w7-assets/icons/shell32_151.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_36", name: "Webcam", svgDataUri: "/w7-assets/icons/imageres_36.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_15", name: "Window", svgDataUri: "/w7-assets/icons/imageres_15.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-imageres_175", name: "Windows Media", svgDataUri: "/w7-assets/icons/imageres_175.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_265", name: "Windows Update", svgDataUri: "/w7-assets/icons/shell32_265.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_261", name: "Wireless", svgDataUri: "/w7-assets/icons/shell32_261.webp", color: "#4A90D9", category: "win7" as const },
  { id: "w7-shell32_179", name: "Zip", svgDataUri: "/w7-assets/icons/shell32_179.webp", color: "#4A90D9", category: "win7" as const }
];

export const ICON_LIBRARY: LibraryIcon[] = [...MS_APPS, ...BROWSER_ICONS, ...SI_ICONS, ...WIN7_ICONS];

export const CATEGORIES: { key: LibraryIcon["category"]; label: string }[] = [
  { key: "win7",        label: "Win7 Native" },
  { key: "microsoft",   label: "Microsoft" },
  { key: "browser",     label: "Browsers" },
  { key: "productivity",label: "Productivity" },
  { key: "dev",         label: "Dev" },
  { key: "creative",    label: "Creative" },
  { key: "social",      label: "Social" },
  { key: "media",       label: "Media" },
  { key: "gaming",      label: "Gaming" },
];
