// Run with: node scripts/generate-icons.mjs
// Reads simple-icons SVGs + metadata, emits lib/icons.generated.ts with inlined data.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const siDir = path.join(root, "node_modules", "simple-icons");
const iconsDir = path.join(siDir, "icons");
const metaPath = path.join(siDir, "data", "simple-icons.json");

// Curated list — { slug: file slug, name: display name, whiteOnly?: render in white }
const CURATED = [
  { slug: "googlechrome", name: "Chrome" },
  { slug: "firefox", name: "Firefox" },
  { slug: "safari", name: "Safari" },
  { slug: "brave", name: "Brave" },
  { slug: "spotify", name: "Spotify" },
  { slug: "discord", name: "Discord" },
  { slug: "whatsapp", name: "WhatsApp" },
  { slug: "telegram", name: "Telegram" },
  { slug: "gmail", name: "Gmail" },
  { slug: "youtube", name: "YouTube" },
  { slug: "netflix", name: "Netflix" },
  { slug: "vscodium", name: "VS Code" },
  { slug: "github", name: "GitHub", whiteOnly: true },
  { slug: "notion", name: "Notion", whiteOnly: true },
  { slug: "figma", name: "Figma" },
  { slug: "blender", name: "Blender" },
  { slug: "steam", name: "Steam", whiteOnly: true },
  { slug: "epicgames", name: "Epic", whiteOnly: true },
  { slug: "obsstudio", name: "OBS" },
  { slug: "vlcmediaplayer", name: "VLC" },
  { slug: "x", name: "X", whiteOnly: true },
  { slug: "instagram", name: "Instagram" },
  { slug: "reddit", name: "Reddit" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "googledrive", name: "Drive" },
];

const meta = JSON.parse(fs.readFileSync(metaPath, "utf8"));
const metaBySlug = Object.fromEntries(meta.map((m) => [m.slug, m]));

const out = [];
for (const { slug, name, whiteOnly } of CURATED) {
  const svgFile = path.join(iconsDir, `${slug}.svg`);
  if (!fs.existsSync(svgFile)) {
    console.warn(`Skipping ${slug} — file not found`);
    continue;
  }
  const m = metaBySlug[slug];
  if (!m) {
    console.warn(`Skipping ${slug} — no metadata`);
    continue;
  }
  const svg = fs.readFileSync(svgFile, "utf8");
  const fill = whiteOnly ? "ffffff" : m.hex;
  const colored = svg.replace("<svg ", `<svg fill="#${fill}" `);
  const dataUri = `data:image/svg+xml;base64,${Buffer.from(colored).toString("base64")}`;
  out.push({ id: slug, name, color: `#${m.hex}`, svgDataUri: dataUri });
}

const fileBody = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
export type LibraryIcon = {
  id: string;
  name: string;
  color: string;
  svgDataUri: string;
};

export const ICON_LIBRARY: LibraryIcon[] = ${JSON.stringify(out, null, 2)};
`;

const outPath = path.join(root, "lib", "icons.generated.ts");
fs.writeFileSync(outPath, fileBody);
console.log(`Wrote ${out.length} icons to ${outPath}`);
